# Generated by Django 3.2.3 on 2021-05-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210529_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heart',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=10)),
                ('chest_pain', models.CharField(max_length=5)),
                ('blood_pressure', models.CharField(max_length=5)),
                ('cholestoral', models.CharField(max_length=5)),
                ('fasting_blood', models.CharField(max_length=5)),
                ('restecg', models.CharField(max_length=5)),
                ('max_heart', models.CharField(max_length=5)),
                ('exang', models.CharField(max_length=5)),
                ('old_peak', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Hearts',
        ),
    ]
