# Generated by Django 3.2.3 on 2021-05-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210529_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='heart',
            name='ca',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='heart',
            name='slope',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='heart',
            name='thal',
            field=models.CharField(default=1, max_length=2),
        ),
    ]
