# Generated by Django 3.2.3 on 2021-05-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210529_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diabetes',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=5)),
                ('glucose', models.CharField(max_length=5)),
                ('blood_pressure', models.CharField(max_length=5)),
                ('skin_thickness', models.CharField(max_length=5)),
                ('insulin', models.CharField(max_length=5)),
                ('BMI', models.CharField(max_length=5)),
                ('DiabetesPedigreeFunction', models.CharField(max_length=5)),
            ],
        ),
    ]
